apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: wordsmith
spec:
  clusterIP: None
  selector:
    app: wordsmith-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordsmith-db
  namespace: wordsmith
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-db
  template:
    metadata:
      labels:
        app: wordsmith-db
    spec:
      containers:
        - name: db
          image: dockersamples/k8s-wordsmith-db:latest
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordsmith-db-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: database-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi